config/routes.rb
Bellsof::Application.routes.draw do

  get "sessions/new"

  get "sessions/login"
  get "sessions/logout"
  get "photos/index"
  get "photos/photos2"
  get "photos/photos3"
  get "photos/photos4"
  get "photos/photos5"
  get "photos/photos6"
  get "photos/photos7"
  get "photos/photos8"
  get "music/index"
  resources :posts, :sessions

  match '/posts', :to => 'posts#index'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  get "home/index"

  match 'index2', :to => 'home#index2'

  root :to => "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authorize, :except => :index
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to posts_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      #flash[:success] = "Welcome to the Sample App!"
      #redirect_to @user
    else
      #@title = "Sign up"
      #render 'new'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def no_space(string)
      string.gsub(" ", "")
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private
    def authorize 
      unless signed_in?
        redirect_to home_path
        false
      end
    end

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index2.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Bells Of..</title>
  <%= stylesheet_link_tag "basic", "galleria" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
<ul id="primary">
  <li><span>Home</span></li>
  <li><%= link_to "Music", music_index_path %></li>
  <li><%= link_to "Words", posts_path %></li>
  <li><%= link_to "Photos", photos_index_path %></li>
</ul>
</div>

<div id="main">
  <div style="text-align: center"><p><h2 style="border-bottom: none">NEW 12" OUT NOW: <a href="http://teenbeatrecords.com/items/503.html">"Bells Of 00/85"</h2></a></p>
  <%= image_tag "bells_site-image.jpg" %>
  </div>

  <div id="contents">
    <h2>Welcome to one the World's *Best* BELLS OF.. Websites</h2>
    <p>BELLS OF.. was formed one fine day in 1985 as a music project of Lawrence McDonald.</p>
    <p>The project continues to this day. BELLS OF.. has begun, and BELLS OF.. has no end.</p>
    <p>Contact BELLS OF: <a href="mailto:quindocquafarms@gmail.com">quindocquafarms@gmail.com</a></p>
    <%= image_tag "peterquinnbellsof.jpg" %>
    <div id="contents2">

      <p>=~=~=~=</p>
      <p id="wallenda"><b>Wallenda</b><br /></p>
      <p>Wire, wire holding tight<br />
         Pulling poles with all your might<br />
         What unbalanced thought in mind<br />
         Could tip the man upon your line</p>
      <p>=~=~=~=</p>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

<script src="https://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1848000-1";
urchinTracker();
</script>

</body>
</html>

app/views/layouts/_footer.html.erb
<div id="footer">
  <p>Design &copy; 2007-<%=Time.now.year%>  chorographics | Poetry, lyrics, stories &copy; 2007-<%=Time.now.year%> Lawrence McDonald, BELLS OF.. |
<% if signed_in? %>
    <%= link_to "Sign out", logout_path, :method => :delete %>
    <% else %>
    <%= link_to "Sign in", login_path %>
  <% end %> </p>
</div>

app/views/layouts/application.html.erb
<%= yield %>
<%= debug(params) if Rails.env.development? %>

app/views/photos/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Bells of..</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="imagetoolbar" content="false">
    <meta name="description" content="">
    <meta name="keywords" content="">
	<%= stylesheet_link_tag "basic.css"%>
	<%= stylesheet_link_tag "galleria.css", {:rel => "stylesheet", :type => "text/css", :media => "screen" } %>

	<%= javascript_include_tag "jquery.min.js" %>
	<%= javascript_include_tag "jquery.galleria.js" %>

        <script type="text/javascript">
	$(document).ready(function(){

		$('.gallery_demo_unstyled').addClass('gallery_demo'); // adds new class name to maintain degradability

		$('ul.gallery_demo').galleria({
			history   : true, // activates the history object for bookmarking, back-button etc.
			clickNext : true, // helper for making the image clickable
			insert    : '#main_image', // the containing selector for our main image
			onImage   : function(image,caption,thumb) { // let's add some image effects for demonstration purposes

				// fade in the image & caption
				image.css('display','none').fadeIn(1000);
				caption.css('display','none').fadeIn(1000);

				// fetch the thumbnail container
				var _li = thumb.parents('li');

				// fade out inactive thumbnail
				_li.siblings().children('img.selected').fadeTo(500,0.3);

				// fade in active thumbnail
				thumb.fadeTo('fast',1).addClass('selected');

				// add a title for the clickable image
				image.attr('title','Next image >>');
			},
			onThumb : function(thumb) { // thumbnail effects goes here

				// fetch the thumbnail container
				var _li = thumb.parents('li');

				// if thumbnail is active, fade all the way.
				var _fadeTo = _li.is('.active') ? '1' : '0.3';

				// fade in the thumbnail when finnished loading
				thumb.css({display:'none',opacity:_fadeTo}).fadeIn(1500);

				// hover effects
				thumb.hover(
					function() { thumb.fadeTo('fast',1); },
					function() { _li.not('.active').children('img').fadeTo('fast',0.3); } // don't fade out if the parent is active
				)
			}
		});
	});


	</script>
    <style media="screen,projection" type="text/css">

	/* BEGIN DEMO STYLE */
	*{margin:0;padding:0}

	.caption{color:#888;position:absolute;top:330px;left:603px;width:200px;}
	.demo{position:relative;margin-top:2em;}
	.gallery_demo{width:200px;float:left;}
	.gallery_demo li{width:55px;height:70px;border:3px double #eee;margin: 0 2px 2px 0;background:#eee;}
	.gallery_demo li.hover{border-style:solid;border-color:#222222;}
	.gallery_demo li.active{border-style:solid;border-color:#222;}
	.gallery_demo li div{left:240px}
	.gallery_demo li div .caption{font:italic 0.7em/1.4 georgia,serif;}

	.galleria_container{margin:0 auto 60px auto;height:438px;width:600px;float:left;}

	.nav{padding-top:15px;clear:both;}

	.info{text-align:left;margin:30px 0;border-top:1px dotted #221;padding-top:30px;clear:both;}
	.info p{margin-top:1.6em;}

	.nav{position:absolute;top:410px;left:0;}

    </style>

</head>

<body>

<div id="header">
<ul id="primary">
  <li><%= link_to "Home", home_index_path %></li>
  <li><%= link_to "Music", music_index_path %></li>
  <li><%= link_to "Words", posts_path %></li>
  <li><span>Photos</span></li>
</ul>
</div>
<div id="main" style="padding-top:.35em;">
  <div id="contents" style="height:535px">
    <div id="photolink">
            page 01 | <a href="photos2.html">02</a> | <a href="photos3.html">03</a> | <a href="photos4.html">04</a> | <a href="photos5.html">05</a> | <a href="photos6.html">06</a> | <a href="photos7.html">07</a> | <a href="photos8.html">08</a>
    </div>

    <div class="demo">
      <ul class="gallery_demo_unstyled">
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/bells_pool.jpg", {:alt => "Bells Pool", :title => "Bells Pool"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/busandfield0.jpg", {:alt => "Bus and Field", :title => "Bus and Field"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/corner_air_oc.jpg", {:alt => "Corner Air", :title => "Corner Air"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/adj0.jpg", {:alt => "Adj", :title => "Adj"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/arlington.jpg", {:alt => "Arlington", :title =>"Arlington"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/bass_0.jpg", {:alt => "Bass", :title => "Bass"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/andy0.jpg", {:alt => "Andycane", :title =>"Andycane"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/bells1985_0.jpg", {:alt => "Bells 1985", :title => "Bells 1985"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/bells1986_0.jpg", {:alt => "Bells 1986", :title=> "Bells 1986"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/melons0.jpg", {:alt => "Melons", :title => "Melons"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/recording2004.jpg", {:alt => "Recording 2004", :title => "Recording 2004"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/nate_cccc2.jpg", {:alt => "Nate CCCC", :title => "Nate CCCC"}%></li>
      </ul>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

<script src="https://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1848000-1";
urchinTracker();
</script>

</body>
</html>

app/views/photos/photos2.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Bells of..</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="imagetoolbar" content="false">
    <meta name="description" content="">
    <meta name="keywords" content="">
	<%= stylesheet_link_tag "basic.css"%>
	<%= stylesheet_link_tag "galleria.css", {:rel => "stylesheet", :type => "text/css", :media => "screen" } %>

	<%= javascript_include_tag "jquery.min.js" %>
	<%= javascript_include_tag "jquery.galleria.js" %>

        <script type="text/javascript">
	$(document).ready(function(){

		$('.gallery_demo_unstyled').addClass('gallery_demo'); // adds new class name to maintain degradability

		$('ul.gallery_demo').galleria({
			history   : true, // activates the history object for bookmarking, back-button etc.
			clickNext : true, // helper for making the image clickable
			insert    : '#main_image', // the containing selector for our main image
			onImage   : function(image,caption,thumb) { // let's add some image effects for demonstration purposes

				// fade in the image & caption
				image.css('display','none').fadeIn(1000);
				caption.css('display','none').fadeIn(1000);

				// fetch the thumbnail container
				var _li = thumb.parents('li');

				// fade out inactive thumbnail
				_li.siblings().children('img.selected').fadeTo(500,0.3);

				// fade in active thumbnail
				thumb.fadeTo('fast',1).addClass('selected');

				// add a title for the clickable image
				image.attr('title','Next image >>');
			},
			onThumb : function(thumb) { // thumbnail effects goes here

				// fetch the thumbnail container
				var _li = thumb.parents('li');

				// if thumbnail is active, fade all the way.
				var _fadeTo = _li.is('.active') ? '1' : '0.3';

				// fade in the thumbnail when finnished loading
				thumb.css({display:'none',opacity:_fadeTo}).fadeIn(1500);

				// hover effects
				thumb.hover(
					function() { thumb.fadeTo('fast',1); },
					function() { _li.not('.active').children('img').fadeTo('fast',0.3); } // don't fade out if the parent is active
				)
			}
		});
	});


	</script>
    <style media="screen,projection" type="text/css">

	/* BEGIN DEMO STYLE */
	*{margin:0;padding:0}

	.caption{color:#888;position:absolute;top:330px;left:603px;width:200px;}
	.demo{position:relative;margin-top:2em;}
	.gallery_demo{width:200px;float:left;}
	.gallery_demo li{width:55px;height:70px;border:3px double #eee;margin: 0 2px 2px 0;background:#eee;}
	.gallery_demo li.hover{border-style:solid;border-color:#222222;}
	.gallery_demo li.active{border-style:solid;border-color:#222;}
	.gallery_demo li div{left:240px}
	.gallery_demo li div .caption{font:italic 0.7em/1.4 georgia,serif;}

	.galleria_container{margin:0 auto 60px auto;height:438px;width:600px;float:left;}

	.nav{padding-top:15px;clear:both;}

	.info{text-align:left;margin:30px 0;border-top:1px dotted #221;padding-top:30px;clear:both;}
	.info p{margin-top:1.6em;}

	.nav{position:absolute;top:410px;left:0;}

    </style>

</head>

<body>

<div id="header">
<ul id="primary">
  <li><%= link_to "Home", home_index_path %></li>
  <li><%= link_to "Music", music_index_path %></li>
  <li><%= link_to "Words", posts_path %></li>
  <li><span>Photos</span></li>
</ul>
</div>
<div id="main" style="padding-top:.35em;">
  <div id="contents" style="height:535px">
    <div id="photolink">
            page 01 | <a href="photos2.html">02</a> | <a href="photos3.html">03</a> | <a href="photos4.html">04</a> | <a href="photos5.html">05</a> | <a href="photos6.html">06</a> | <a href="photos7.html">07</a> | <a href="photos8.html">08</a>
    </div>

    <div class="demo">
      <ul class="gallery_demo_unstyled">
         <li><%= image_tag "https://bellspics.s3.amazonaws.com/spring07b.jpg", {:alt => "Spring 2007", :title => "Spring 2007"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/ceramics.jpg", {:alt => "Ceramics", :title => "Ceramics"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/trail.jpg", {:alt => "Trail", :title => "Trail"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/hd_cccc.jpg", {:alt => "Hound Dog CCCC", :title => "Hound Dog CCCC"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/lmd_polaroid_umbrella0.jpg", {:alt => "Bells", :title =>"Bells"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/bowl.jpg", {:alt => "Bowl", :title => "Bowl"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/buck0.jpg", {:alt => "Buck", :title =>"Buck"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/jason_jonesbridge85.jpg", {:alt => "Jason, Jones Bridge 1985", :title => "Jason, Jones Bridge 1985"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/marsh0.jpg", {:alt => "Marshland", :title=> "Marshland"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/melonfields00.jpg", {:alt => "Melon Fields 2000", :title => "Melon Fields 2000"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/ocean_city0.jpg", {:alt => "Ocean City", :title => "Ocean City"}%></li>
        <li><%= image_tag "https://bellspics.s3.amazonaws.com/main.jpg", {:alt => "Hall", :title => "Hall"}%></li>
      </ul>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

<script src="https://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1848000-1";
urchinTracker();
</script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Bells Of..</title>
  <%= stylesheet_link_tag "basic", "galleria" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</body></html>

app/views/posts/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Bells Of..</title>
  <%= stylesheet_link_tag "basic", "galleria" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
<ul id="primary">
  <li><%= link_to "Home", home_index_path %></li>
  <li><%= link_to "Music", music_index_path %></li>
  <li><span>Words</span></li>
  <li><%= link_to "Photos", photos_index_path %></li>
</ul>
</div>
<div id="main">
  <div id="leftcol2">
    <h2 id="titles">BELLS OF.. LYRICS | POETRY | STORIES | WORDS </h2>
    <% if signed_in? %>
      <b><%= link_to '** NEW POST', new_post_path %></b>
    <% end %>

    <p>
    <% @posts.each do |post| %>
      <%= link_to post.title, {:anchor => no_space(post.title)} %> <br />
    <% end %>
    </p>

    <p>=~=~=~=~=~=~=~=~=~=~=~=</p>
    
    <% @posts.each do |post| %>
      <p id=<%= no_space(post.title)%> ><b><%= post.title %></b></p>
      <p><%= simple_format(post.content) %></p>

    <p><%= link_to "Return to top", {:anchor => "titles"} %></p>

    <% if signed_in? %>
      <td><b><%= link_to 'EDIT', edit_post_path(post) %></td>
       ||
      <td><%= link_to 'DELETE', post, :confirm => 'Are you sure?', :method => :delete %></b></td>
    <% end %>
    <p>=~=~=~=~=~=~=~=~=~=~=~=</p>
        
    <% end %>

    <br />
  </div>
</div>

<%= render 'layouts/footer' %>


<script src="https://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1848000-1";
urchinTracker();
</script>

</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Bells Of..</title>
  <%= stylesheet_link_tag "basic", "galleria" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

</body></html>

app/views/posts/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Bells Of..</title>
  <%= stylesheet_link_tag "basic", "galleria" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back to Words page', posts_path %>

</body></html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>